### ISSUE TITLE
Not Working with XAMMP

### ISSUE THREAD

**Issue by servitecbaires** [GiovanniSalmeri/yellow-filelist#2]
Hello! 
I'm trying to test the plugin running XAMMP stack on win10 (aka WAMP) and is not working.
The page display the shortcode as a piece of text on screen: [filelist].
I noticied the plugin also not create "filelist" folder as pubished in the documentation.
I hope you understand my poor english.
Thanks for your time and work!
Marto

**Comment by GiovanniSalmeri** [comment]
I am very sorry for the abysmally late reply :-( Apparently I forgot completely your message. Unfortunately I have no experience of XAMMP, so I do not know if there is something wrong with Windows. But I suspect that the problem is elsewhere: the folder "filelist" is not created by the extension: it must be manually created and populated with the files to be downloaded. If there is no such folder, it is normal that the shortcode is shown as bare text.

**Comment by servitecbaires** [comment]
> 

I appreciate your answer anyway. 
Many thanks for taking your time for support this software and the extensions that you kindly share with us.
